import Header from '@/app/Components/Layout_components/Header/Header';
import Footer from '@/app/Components/Layout_components/Footer/Footer'
import "./globals.css";

export const metadata = {
  title: "Gelateria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
